ARG BASE_IMAGE=nvidia/cudagl:11.3.0-devel-ubuntu20.04
FROM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# NVIDIA key issue rectification
RUN apt-key del 7fa2af80
RUN apt-get update && apt-get install -y --no-install-recommends wget
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb
RUN dpkg -i cuda-keyring_1.0-1_all.deb

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils

RUN python3 -m pip install --upgrade pip

RUN apt-get install -y python3-setuptools

RUN pip3 install wheel numpy msgpack-rpc-python python-dev-tools

RUN export CPLUS_INCLUDE_PATH=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")

RUN export Python3_INCLUDE_DIRS=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")

# install vulkan

RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:graphics-drivers/ppa

RUN apt-get update && apt-get -y upgrade

RUN apt install -y nvidia-settings vulkan-utils vulkan-tools

# install nvidia drivers

RUN apt install -y ubuntu-drivers-common

RUN apt-get install -y nvidia-driver-550

RUN pip install opencv-contrib-python==4.5.5.64 --verbose

RUN pip install airsim

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser airsim_user sudo && \
	adduser airsim_user audio && \
	adduser airsim_user video

USER airsim_user
WORKDIR /home/airsim_user

RUN mkdir -p /home/airsim_user/Documents/AirSim
COPY settings.json /home/airsim_user/Documents/AirSim
#ADD Documents /home/airsim_user/Documents

RUN sudo chown -R airsim_user /home/airsim_user
